version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    networks:
      - lviv-network

networks:
  lviv-network:
    driver: bridge